Fix 3.7 Yield Issue
Fixing an error we get trying to use this library with python 3.7:
struct.error: unpack requires a buffer of 4 bytes
StopIteration: unpack requires a buffer of 4 bytes
Fix detailed here: https://stackoverflow.com/a/51701040